name: Possibility and Probability
description: Trying out markdown for everything

permalink: /:year/:month/:title
baseurl: 

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true
  
remote_theme: nloadholtes/hacker

google_analytics_key: UA-247234-1

plugins:
  - jekyll-sitemap
