name: Possibility and Probability
description: A Python programmer with a personality thinking about space exploration
title: Possibility and Probability

permalink: /:year/:month/:title
baseurl:

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

# A custom theme  
remote_theme: nloadholtes/hacker

# google_analytics_key: UA-247234-4
# sumo_id: d8f4d994836230737eb45859018e89483c6fa080c4a91ba776c91bdeab8fb6f9
# addthis_key: ra-5659ccd9e966d5d5

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
